CREATE TABLE IF NOT EXISTS public.lexical_duplicate_sets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  duplicate_set_key text NOT NULL UNIQUE,
  normalized_word_set text NOT NULL,
  duplicate_count integer NOT NULL,
  canonical_group_id bigint REFERENCES public.lexical_groups(id) ON DELETE SET NULL,
  duplicate_type text NOT NULL DEFAULT 'exact',
  decision_status text NOT NULL DEFAULT 'pending',
  notes text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT lexical_duplicate_sets_duplicate_type_check
    CHECK (duplicate_type IN ('exact', 'near', 'subset', 'manual')),
  CONSTRAINT lexical_duplicate_sets_decision_status_check
    CHECK (decision_status IN ('pending', 'reviewed', 'resolved', 'ignored'))
);

CREATE TABLE IF NOT EXISTS public.lexical_duplicate_groups (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  duplicate_set_id bigint REFERENCES public.lexical_duplicate_sets(id) ON DELETE CASCADE,
  group_id bigint REFERENCES public.lexical_groups(id) ON DELETE CASCADE,
  source_id integer,
  group_label text,
  quality_level text,
  review_status text,
  risk_level text,
  is_active boolean,
  is_playable boolean,
  canonical_candidate_score integer NOT NULL DEFAULT 0,
  is_canonical_candidate boolean NOT NULL DEFAULT false,
  suggested_action text NOT NULL DEFAULT 'review',
  created_at timestamptz DEFAULT now(),
  CONSTRAINT lexical_duplicate_groups_set_group_unique UNIQUE (duplicate_set_id, group_id)
);

CREATE INDEX IF NOT EXISTS lexical_duplicate_groups_set_id_idx
  ON public.lexical_duplicate_groups(duplicate_set_id);

CREATE INDEX IF NOT EXISTS lexical_duplicate_groups_group_id_idx
  ON public.lexical_duplicate_groups(group_id);

DROP VIEW IF EXISTS public.lexical_duplicate_summary;
DROP VIEW IF EXISTS public.lexical_duplicate_exact_view;

CREATE OR REPLACE VIEW public.lexical_duplicate_exact_view AS
WITH distinct_words AS (
  SELECT
    w.group_id,
    lower(btrim(w.word)) AS normalized_word,
    min(btrim(w.word)) AS display_word
  FROM public.lexical_words w
  WHERE nullif(btrim(w.word), '') IS NOT NULL
  GROUP BY w.group_id, lower(btrim(w.word))
),
group_word_sets AS (
  SELECT
    g.id AS group_id,
    string_agg(dw.normalized_word, ' / ' ORDER BY dw.normalized_word) AS normalized_word_set,
    string_agg(dw.display_word, ' / ' ORDER BY dw.normalized_word) AS group_label
  FROM public.lexical_groups g
  JOIN distinct_words dw ON dw.group_id = g.id
  GROUP BY g.id
),
group_rows AS (
  SELECT
    gws.normalized_word_set,
    gws.group_id,
    c.source_id,
    coalesce(c.group_label, gws.group_label) AS group_label,
    c.quality_level,
    c.review_status,
    c.is_active,
    c.is_playable
  FROM group_word_sets gws
  LEFT JOIN public.lexical_corpus_coverage c ON c.id = gws.group_id
)
SELECT
  normalized_word_set,
  count(*)::integer AS duplicate_count,
  array_agg(group_id ORDER BY group_id) AS group_ids,
  array_agg(source_id ORDER BY group_id) AS source_ids,
  array_agg(group_label ORDER BY group_id) AS labels,
  array_agg(quality_level ORDER BY group_id) AS quality_levels,
  array_agg(review_status ORDER BY group_id) AS review_statuses,
  array_agg(coalesce(is_active, false) ORDER BY group_id) AS active_flags,
  array_agg(coalesce(is_playable, false) ORDER BY group_id) AS playable_flags
FROM group_rows
GROUP BY normalized_word_set
HAVING count(*) > 1
ORDER BY count(*) DESC, normalized_word_set ASC;

CREATE OR REPLACE VIEW public.lexical_duplicate_summary AS
WITH exact_sets AS (
  SELECT
    normalized_word_set,
    duplicate_count,
    active_flags,
    playable_flags
  FROM public.lexical_duplicate_exact_view
),
expanded AS (
  SELECT
    normalized_word_set,
    unnest(active_flags) AS is_active,
    unnest(playable_flags) AS is_playable
  FROM exact_sets
)
SELECT
  (SELECT count(*)::integer FROM exact_sets) AS duplicate_set_count,
  (SELECT coalesce(sum(duplicate_count), 0)::integer FROM exact_sets) AS duplicated_group_count,
  (SELECT count(*)::integer FROM expanded WHERE is_active = true) AS active_duplicated_group_count,
  (SELECT count(*)::integer FROM expanded WHERE is_playable = true) AS playable_duplicated_group_count,
  (SELECT count(*)::integer FROM exact_sets) AS exact_duplicate_set_count,
  (
    SELECT count(*)::integer
    FROM exact_sets es
    LEFT JOIN public.lexical_duplicate_sets ds ON ds.normalized_word_set = es.normalized_word_set
    WHERE coalesce(ds.decision_status, 'pending') = 'pending'
  ) AS pending_duplicate_set_count,
  (
    SELECT count(*)::integer
    FROM exact_sets es
    JOIN public.lexical_duplicate_sets ds ON ds.normalized_word_set = es.normalized_word_set
    WHERE ds.decision_status = 'resolved'
  ) AS resolved_duplicate_set_count;

CREATE OR REPLACE FUNCTION public.refresh_lexical_duplicate_audit()
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
  DELETE FROM public.lexical_duplicate_groups;
  DELETE FROM public.lexical_duplicate_sets;

  WITH distinct_words AS (
    SELECT
      w.group_id,
      lower(btrim(w.word)) AS normalized_word,
      min(btrim(w.word)) AS display_word
    FROM public.lexical_words w
    WHERE nullif(btrim(w.word), '') IS NOT NULL
    GROUP BY w.group_id, lower(btrim(w.word))
  ),
  group_word_sets AS (
    SELECT
      g.id AS group_id,
      string_agg(dw.normalized_word, ' / ' ORDER BY dw.normalized_word) AS normalized_word_set,
      string_agg(dw.display_word, ' / ' ORDER BY dw.normalized_word) AS group_label
    FROM public.lexical_groups g
    JOIN distinct_words dw ON dw.group_id = g.id
    GROUP BY g.id
  ),
  duplicate_sets AS (
    SELECT
      normalized_word_set,
      md5(normalized_word_set) AS duplicate_set_key,
      count(*)::integer AS duplicate_count
    FROM group_word_sets
    GROUP BY normalized_word_set
    HAVING count(*) > 1
  ),
  group_rows AS (
    SELECT
      ds.duplicate_set_key,
      ds.normalized_word_set,
      ds.duplicate_count,
      gws.group_id,
      c.source_id,
      coalesce(c.group_label, gws.group_label) AS group_label,
      c.quality_level,
      c.review_status,
      c.risk_level,
      c.is_active,
      c.is_playable,
      (
        CASE c.quality_level
          WHEN 'platinum' THEN 50
          WHEN 'gold' THEN 35
          WHEN 'silver' THEN 20
          ELSE 0
        END
        + CASE WHEN c.is_playable = true THEN 10 ELSE 0 END
        + CASE WHEN c.is_active = true THEN 8 ELSE 0 END
        + CASE c.review_status
          WHEN 'reviewed_safe' THEN 8
          WHEN 'reviewed_context_needed' THEN 6
          WHEN 'reviewed_register_sensitive' THEN 6
          ELSE 0
        END
        - CASE WHEN c.risk_level = 'high' THEN 30 ELSE 0 END
        - CASE WHEN c.is_active = false THEN 30 ELSE 0 END
      )::integer AS canonical_candidate_score
    FROM duplicate_sets ds
    JOIN group_word_sets gws ON gws.normalized_word_set = ds.normalized_word_set
    LEFT JOIN public.lexical_corpus_coverage c ON c.id = gws.group_id
  ),
  ranked AS (
    SELECT
      group_rows.*,
      row_number() OVER (
        PARTITION BY normalized_word_set
        ORDER BY canonical_candidate_score DESC, group_id ASC
      ) AS canonical_rank
    FROM group_rows
  ),
  inserted_sets AS (
    INSERT INTO public.lexical_duplicate_sets (
      duplicate_set_key,
      normalized_word_set,
      duplicate_count,
      canonical_group_id,
      duplicate_type,
      decision_status
    )
    SELECT
      duplicate_set_key,
      normalized_word_set,
      duplicate_count,
      group_id AS canonical_group_id,
      'exact',
      'pending'
    FROM ranked
    WHERE canonical_rank = 1
    RETURNING id, duplicate_set_key, canonical_group_id
  )
  INSERT INTO public.lexical_duplicate_groups (
    duplicate_set_id,
    group_id,
    source_id,
    group_label,
    quality_level,
    review_status,
    risk_level,
    is_active,
    is_playable,
    canonical_candidate_score,
    is_canonical_candidate,
    suggested_action
  )
  SELECT
    inserted_sets.id,
    ranked.group_id,
    ranked.source_id,
    ranked.group_label,
    ranked.quality_level,
    ranked.review_status,
    ranked.risk_level,
    ranked.is_active,
    ranked.is_playable,
    ranked.canonical_candidate_score,
    ranked.group_id = inserted_sets.canonical_group_id,
    CASE
      WHEN ranked.group_id = inserted_sets.canonical_group_id THEN 'keep_as_canonical'
      WHEN ranked.is_active = false THEN 'already_inactive'
      ELSE 'disable_duplicate_after_review'
    END AS suggested_action
  FROM ranked
  JOIN inserted_sets ON inserted_sets.duplicate_set_key = ranked.duplicate_set_key;
END;
$$;

GRANT SELECT ON public.lexical_duplicate_sets TO authenticated;
GRANT SELECT ON public.lexical_duplicate_groups TO authenticated;
GRANT SELECT ON public.lexical_duplicate_exact_view TO authenticated;
GRANT SELECT ON public.lexical_duplicate_summary TO authenticated;
